package com.huejie.osmdroid.model.books;

import org.litepal.annotation.Column;
import org.litepal.annotation.Table;

/**
 * 挡土墙外业调查记录簿
 */
@Table("tunnel_engineering_record_book")
public class TunnelEngineeringRecordBook extends BookSimple {

    @Column(columeName = "name")
    public String name;
    @Column(columeName = "technical_standard")
    public String technical_standard;
    @Column(columeName = "left_start_stake")
    public String left_start_stake;
    @Column(columeName = "left_end_stake")
    public String left_end_stake;
    @Column(columeName = "right_start_stake")
    public String right_start_stake;
    @Column(columeName = "right_end_stake")
    public String right_end_stake;
    @Column(columeName = "flat_curve_stake_left")
    public String flat_curve_stake_left;
    @Column(columeName = "flat_curve_stake_right")
    public String flat_curve_stake_right;
    @Column(columeName = "vertical_curve_stake_left")
    public String vertical_curve_stake_left;
    @Column(columeName = "vertical_curve_stake_right")
    public String vertical_curve_stake_right;
    @Column(columeName = "left_inlet_boundary_stake")
    public String left_inlet_boundary_stake;
    @Column(columeName = "right_inlet_boundary_stake")
    public String right_inlet_boundary_stake;
    @Column(columeName = "left_outlet_boundary_stake")
    public String left_outlet_boundary_stake;
    @Column(columeName = "right_outlet_boundary_stake")
    public String right_outlet_boundary_stake;
    @Column(columeName = "contact_channel_inlet_satke")
    public String contact_channel_inlet_satke;
    @Column(columeName = "contact_channel_outlet_satke")
    public String contact_channel_outlet_satke;
    @Column(columeName = "climate_characteristics")
    public String climate_characteristics;
    @Column(columeName = "most_wind")
    public String most_wind;
    @Column(columeName = "rainy_season_month")
    public String rainy_season_month;
    @Column(columeName = "dry_season_month")
    public String dry_season_month;
    @Column(columeName = "entry_form_left")
    public String entry_form_left;
    @Column(columeName = "entry_form_right")
    public String entry_form_right;
    @Column(columeName = "entry_hole_stake_left")
    public String entry_hole_stake_left;
    @Column(columeName = "entry_bright_hole_satke_left")
    public String entry_bright_hole_satke_left;
    @Column(columeName = "entry_dark_hole_satke_left")
    public String entry_dark_hole_satke_left;
    @Column(columeName = "entry_bright_hole_form_left")
    public String entry_bright_hole_form_left;
    @Column(columeName = "entry_strength_support_left")
    public String entry_strength_support_left;
    @Column(columeName = "entry_surface_treatment_left")
    public String entry_surface_treatment_left;
    @Column(columeName = "entry_slope_treatment_left")
    public String entry_slope_treatment_left;
    @Column(columeName = "entry_buried_treatment_left")
    public String entry_buried_treatment_left;
    @Column(columeName = "entry_modified_form_left")
    public String entry_modified_form_left;
    @Column(columeName = "entry_hole_stake_right")
    public String entry_hole_stake_right;
    @Column(columeName = "entry_bright_hole_satke_right")
    public String entry_bright_hole_satke_right;
    @Column(columeName = "entry_dark_hole_satke_right")
    public String entry_dark_hole_satke_right;
    @Column(columeName = "entry_bright_hole_form_right")
    public String entry_bright_hole_form_right;
    @Column(columeName = "entry_strength_support_right")
    public String entry_strength_support_right;
    @Column(columeName = "entry_surface_treatment_right")
    public String entry_surface_treatment_right;
    @Column(columeName = "entry_slope_treatment_right")
    public String entry_slope_treatment_right;
    @Column(columeName = "entry_buried_treatment_right")
    public String entry_buried_treatment_right;
    @Column(columeName = "entry_modified_form_right")
    public String entry_modified_form_right;
    @Column(columeName = "exit_form_left")
    public String exit_form_left;
    @Column(columeName = "exit_form_right")
    public String exit_form_right;
    @Column(columeName = "exit_hole_stake_left")
    public String exit_hole_stake_left;
    @Column(columeName = "exit_bright_hole_satke_left")
    public String exit_bright_hole_satke_left;
    @Column(columeName = "exit_dark_hole_satke_left")
    public String exit_dark_hole_satke_left;
    @Column(columeName = "exit_bright_hole_form_left")
    public String exit_bright_hole_form_left;
    @Column(columeName = "exit_strength_support_left")
    public String exit_strength_support_left;
    @Column(columeName = "exit_surface_treatment_left")
    public String exit_surface_treatment_left;
    @Column(columeName = "exit_slope_treatment_left")
    public String exit_slope_treatment_left;
    @Column(columeName = "exit_buried_treatment_left")
    public String exit_buried_treatment_left;
    @Column(columeName = "exit_modified_form_left")
    public String exit_modified_form_left;
    @Column(columeName = "exit_hole_stake_right")
    public String exit_hole_stake_right;
    @Column(columeName = "exit_bright_hole_satke_right")
    public String exit_bright_hole_satke_right;
    @Column(columeName = "exit_dark_hole_satke_right")
    public String exit_dark_hole_satke_right;
    @Column(columeName = "exit_bright_hole_form_right")
    public String exit_bright_hole_form_right;
    @Column(columeName = "exit_strength_support_right")
    public String exit_strength_support_right;
    @Column(columeName = "exit_surface_treatment_right")
    public String exit_surface_treatment_right;
    @Column(columeName = "exit_slope_treatment_right")
    public String exit_slope_treatment_right;
    @Column(columeName = "exit_buried_treatment_right")
    public String exit_buried_treatment_right;
    @Column(columeName = "exit_modified_form_right")
    public String exit_modified_form_right;
    @Column(columeName = "exit_strength_support_right")
    public String hydrologic_conditions;
    @Column(columeName = "tunnel_terrain")
    public String tunnel_terrain;
    @Column(columeName = "poor_geology")
    public String poor_geology;
    @Column(columeName = "surface_building_distribution")
    public String surface_building_distribution;
    @Column(columeName = "pipes_network_distribution")
    public String pipes_network_distribution;
    @Column(columeName = "slag_dump_protective")
    public String slag_dump_protective;
    @Column(columeName = "slag_dump_drainage_measures")
    public String slag_dump_drainage_measures;
    @Column(columeName = "investigation_entry_pavement")
    public String investigation_entry_pavement;
    @Column(columeName = "investigation_exit_pavement")
    public String investigation_exit_pavement;
    @Column(columeName = "survey_entry_water_land")
    public String survey_entry_water_land;
    @Column(columeName = "survey_exit_water_land")
    public String survey_exit_water_land;
    @Column(columeName = "investigation_requisition")
    public String investigation_requisition;
    @Column(columeName = "other_miscellaneous")
    public String other_miscellaneous;
    @Column(columeName = "geophysical_transversely")
    public String geophysical_transversely;
    @Column(columeName = "geophysical_longitudinal")
    public String geophysical_longitudinal;
    @Column(columeName = "slag_dump_site")
    public String slag_dump_site;
    @Column(columeName = "agreement")
    public String agreement;

    @Column(columeName = "tunnel_form")
    public long tunnel_form;
    @Column(columeName = "horizontal_alignment_satisfy_left")
    public long horizontal_alignment_satisfy_left;
    @Column(columeName = "horizontal_alignment_satisfy_right")
    public long horizontal_alignment_satisfy_right;
    @Column(columeName = "vertical_alignment_satisfy_left")
    public long vertical_alignment_satisfy_left;
    @Column(columeName = "vertical_alignment_satisfy_right")
    public long vertical_alignment_satisfy_right;
    @Column(columeName = "inner_contour_attribute")
    public long inner_contour_attribute;
    @Column(columeName = "left_hole_inlet_mode")
    public long left_hole_inlet_mode;
    @Column(columeName = "right_hole_inlet_mode")
    public long right_hole_inlet_mode;
    @Column(columeName = "left_hole_outlet_mode")
    public long left_hole_outlet_mode;
    @Column(columeName = "right_hole_outlet_mode")
    public long right_hole_outlet_mode;
    @Column(columeName = "left_line_length")
    public double left_line_length;
    @Column(columeName = "right_line_length")
    public double right_line_length;
    @Column(columeName = "tunnel_length_left")
    public double tunnel_length_left;
    @Column(columeName = "tunnel_length_right")
    public double tunnel_length_right;
    @Column(columeName = "ultrahigh_left")
    public double ultrahigh_left;
    @Column(columeName = "ultrahigh_right")
    public double ultrahigh_right;
    @Column(columeName = "slope_length_left")
    public double slope_length_left;
    @Column(columeName = "slope_length_right")
    public double slope_length_right;
    @Column(columeName = "entrance_design_elevation_left")
    public double entrance_design_elevation_left;
    @Column(columeName = "entrance_design_elevation_right")
    public double entrance_design_elevation_right;
    @Column(columeName = "entrance_ground_elevation_left")
    public double entrance_ground_elevation_left;
    @Column(columeName = "entrance_ground_elevation_right")
    public double entrance_ground_elevation_right;
    @Column(columeName = "exit_design_elevation_left")
    public double exit_design_elevation_left;
    @Column(columeName = "exit_design_elevation_right")
    public double exit_design_elevation_right;
    @Column(columeName = "exit_ground_elevation_left")
    public double exit_ground_elevation_left;
    @Column(columeName = "exit_ground_elevation_right")
    public double exit_ground_elevation_right;
    @Column(columeName = "inner_contour_r1")
    public double inner_contour_r1;
    @Column(columeName = "inner_contour_r2")
    public double inner_contour_r2;
    @Column(columeName = "inner_contour_r3")
    public double inner_contour_r3;
    @Column(columeName = "inner_contour_r4")
    public double inner_contour_r4;
    @Column(columeName = "total_height_h")
    public double total_height_h;
    @Column(columeName = "total_height_b")
    public double total_height_b;
    @Column(columeName = "headroom_area_arch")
    public double headroom_area_arch;
    @Column(columeName = "headroom_area_road")
    public double headroom_area_road;
    @Column(columeName = "road_width_outside_hole")
    public double road_width_outside_hole;
    @Column(columeName = "distance_traffic")
    public double distance_traffic;
    @Column(columeName = "designed_elevation_distance")
    public double designed_elevation_distance;
    @Column(columeName = "entrance_elevation")
    public double entrance_elevation;
    @Column(columeName = "exit_elevation")
    public double exit_elevation;
    @Column(columeName = "average_air_pressure")
    public double average_air_pressure;
    @Column(columeName = "annual_wind_speed")
    public double annual_wind_speed;
    @Column(columeName = "maximum_wind_speed")
    public double maximum_wind_speed;
    @Column(columeName = "standard_freezing_depth")
    public double standard_freezing_depth;
    @Column(columeName = "maximum_freezing_depth")
    public double maximum_freezing_depth;
    @Column(columeName = "contact_channel_set")
    public long contact_channel_set;
    @Column(columeName = "annual_temperature")
    public long annual_temperature;
    @Column(columeName = "record_high_temperature")
    public long record_high_temperature;
    @Column(columeName = "record_low_temperature")
    public long record_low_temperature;
    @Column(columeName = "average_annual_rainfall")
    public long average_annual_rainfall;
    @Column(columeName = "record_max_rainfall")
    public long record_max_rainfall;
    @Column(columeName = "rainy_season_rainfall")
    public long rainy_season_rainfall;
    @Column(columeName = "dry_season_rainfall")
    public long dry_season_rainfall;
    @Column(columeName = "annual_snowfall_days")
    public long annual_snowfall_days;
    @Column(columeName = "record_max_snowfall")
    public long record_max_snowfall;
    @Column(columeName = "rainy_season_days")
    public long rainy_season_days;
    @Column(columeName = "annual_average_covered_snow_days")
    public long annual_average_covered_snow_days;
    @Column(columeName = "covered_snow_max_days")
    public long covered_snow_max_days;
    @Column(columeName = "max_snow_depth")
    public long max_snow_depth;
    @Column(columeName = "average_annual_fog")
    public long average_annual_fog;
    @Column(columeName = "distribution_season")
    public long distribution_season;
    @Column(columeName = "drilling")
    public long drilling;
    @Column(columeName = "boring")
    public long boring;
    @Column(columeName = "geophysical_transversely_electrical")
    public long geophysical_transversely_electrical;
    @Column(columeName = "geophysical_transversely_seismic")
    public long geophysical_transversely_seismic;
    @Column(columeName = "geophysical_transversely_other")
    public long geophysical_transversely_other;
    @Column(columeName = "geophysical_longitudinal_electrical")
    public long geophysical_longitudinal_electrical;
    @Column(columeName = "geophysical_longitudinal_seismic")
    public long geophysical_longitudinal_seismic;
    @Column(columeName = "geophysical_longitudinal_other")
    public long geophysical_longitudinal_other;
    @Column(columeName = "slag_dump_capacity")
    public long slag_dump_capacity;
    @Column(columeName = "drilling_number")
    public long drilling_number;
    @Column(columeName = "boring_number")
    public long boring_number;
    @Column(columeName = "geophysical_transversely_electrical_strip")
    public long geophysical_transversely_electrical_strip;
    @Column(columeName = "geophysical_transversely_seismic_strip")
    public long geophysical_transversely_seismic_strip;
    @Column(columeName = "geophysical_transversely_other_strip")
    public long geophysical_transversely_other_strip;
    @Column(columeName = "geophysical_longitudinal_electrical_strip")
    public long geophysical_longitudinal_electrical_strip;
    @Column(columeName = "geophysical_longitudinal_seismic_strip")
    public long geophysical_longitudinal_seismic_strip;
    @Column(columeName = "geophysical_longitudinal_other_strip")
    public long geophysical_longitudinal_other_strip;


}
